version: "3"

tasks:
  archive:
    cmds:
      - rm lyceum-nstu-schedule.zip
      - zip -r lyceum-nstu-schedule.zip . -x "*.DS_Store" -x ".idea/*" -x ".git/*"
  tests:clean:
    cmd: go clean -testcache
  tests:
    cmd: go test ./...
  tests:coverage:
    cmds:
      - go test ./... -coverprofile cover.out
      - go tool cover -func cover.out
  tests:coverage-html:
    cmds:
      - go test ./... -coverprofile cover.out
      - go tool cover -html cover.out
