version: "3"

tasks:
  archive:
    cmds:
      - rm lyceum-nstu-schedule.zip || true
      - zip -r lyceum-nstu-schedule.zip . -x "*_test.go" -x "*.DS_Store" -x ".idea/*" -x ".cursor/*" -x ".devcontainer/*" -x ".git/*" -x ".github/*" -x "test/*" -x "Taskfile.yaml" -x ".gitignore" -x "cover.out" -x "lyceum-nstu-schedule"
  tests:clean:
    cmd: go clean -testcache
  tests:
    cmd: go test ./...
  build:
    cmd: go build -v ./...
  run:
    cmd: go run . {{.CLI_ARGS}}
  tests:coverage:
    cmds:
      - go test ./... -coverprofile cover.out
      - go tool cover -func cover.out
  tests:coverage-html:
    cmds:
      - go test ./... -coverprofile cover.out
      - go tool cover -html cover.out
